### ISSUE TITLE
0.2.0 Blockers

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/furrr#151]
CRAN release blockers:

- [x] Next globals release

- [x] `findGlobals(~NULL)` and `findGlobals(quo(NULL))` https://github.com/HenrikBengtsson/globals/issues/59

- [x] Remapping of base globals - https://github.com/HenrikBengtsson/future/issues/401

  - Note, fixed by https://github.com/HenrikBengtsson/globals/pull/55, which I have a Remote against

- [x] Progress and dplyr - https://github.com/HenrikBengtsson/progressr/issues/83

  - Decide on whether or not `.progress` in furrr should stick around, but internally use progressr.

  - Related is the return value of `with_progress()` for use in dplyr `mutate()` https://github.com/HenrikBengtsson/progressr/issues/26

  - Update: Decided to keep the old `.progress` bar for the next release, with some notes about it eventually going away. See #160 

- [x] `purrr::modify()` might be tweaked a little tidyverse/purrr#754

  - I'm happy to release without waiting on this. Can always do a small update later

- [x] Follow up on https://github.com/abjur/abjutils/issues/15

**Comment by clente** [comment]
`abjutils` should no longer be a problem! Thanks again :smile:

**Comment by DavisVaughan** [comment]
Thank you @clente!
